Name: Build and deploy Node.js app to Azure Web App - cloud-task-manager-frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Build
        run: |
          npm install
          npm run build
        working-directory: ./frontend
        env:
          VITE_API_URL: "https://cloud-task-manager-api-95559-bqd3etcggghqbjdu.germanywestcentral-01.azurewebsites.net/api"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: frontend/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BCB45A4B84714FE7976D1CF73DB79B44 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_967BE461E430471C927F03761B9F0072 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_84377C8F6AEA4810AB1E88DA9FE6C54B }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cloud-task-manager-frontend-95559'
          package: dist
          startup-command: "pm2 serve /home/site/wwwroot --no-daemon --spa"
          package: .
          
